import q2_helpers
import sys
import math
import random
import numpy as np
import logging
from datetime import datetime

random.seed(datetime.now())

ciphertext = "DUFEODSFPXFQDZUWODIDQTGPKMXODPBYAZZDFOEODWLFHFURPRRNAPIAURLUOAOMUKFZFQVLGONMQILDDPQRZWADLDIGLIURXFWZFZFQRHIUAPRPOUUQODGPKMXOURNHXVXOZDLDTVPRLTLDUXHFPRRDEONSEOFHEUPRRDZLOSDQQFAOEOIPIPSTURUOGPEZGHRKHCFQPDNHQIDIFHAXLQOFSERTQFAZOHOBDVVLAPHPAIPIULDOUHSOEOOMUTLQPHRDRKURDLSIDWFSOWPIIMGRONOMUFODTUAOTXGPKMXONAIULDXUGNRUBYWORTQFVPZNGOPRURFEGOAPQYMIXOEVAMPAGOCILDGHRKHCFHAMMIAPUPLDDSVXONAVMILDUXDZOFSETURUPIPOURFHLDDEAUOFOFAPDQQFPHLDAPAIAPRKURDETUHCNLTIVCXFFDVTGSAXXOHDZNQIOFZEAMPMDZSXSIURFHGPKMXOLDHFLWOYIANUONMUVMLNVXEOMUVMLNVXRKURFEMOZDVAHYOULIUPDUWDSFAPRKURQLLYGDQFRDADQHURDLSIDWAPEQLFUVLNQIVLNAVXYLYVMONHQILDIGADIPAXGPIWUIGSNXXVLFGDYBZWSRUCAPRKURFHFEFHDEAGDECSPRLTWDANVIFZFQBSXVAOVZVDMSHUGPKMXONUURPUPRDECUHFWDZWXVGOVITGRDEOYHPYGMYBAVHTUPAPUKOFBPANNMIVNDYBEVSNFHBSFHNDQFLFUVRDEOGPKMXOOFSZTIADNUURVXHFOFSZITVZGHOFCKYHXOLNDOONOFAEYHRKHQHFOHQILDUIFZWDOFSZYBLDDAPIDVTUHCFESVANNEODODXOVZYZIAPMGPKMXOIHDUGOVOEODSXVZCGOVOGDONZWUQFZFQVIFZFQXSQMPYMIXOOFOZHIBIITONGOXFMGLQLFUVVIPRFNHYIPDVTUHCNLTIYEIDRDZERGDZDPGDONMOURDZUVGPKMXOVISVATORITWDAPUQRTEDDUWDIPPAGDPMGOLNOVFHVLPRURWDUIOFLNOFSZFDHURNHYOULIUPGPKMXODUFQPITGDZGPIGONIPFSHALDVXVISISPQRLDWTFZFHWDCKNDDCWDLDRDZDLFUAFZFQAPRKURWLEFHFOMRPBUGNODURNLIAEQNACZDUDLOADVFSWBZWFQYBDZIPUYIQNHURFHEFHFURWLLFUVOBDVEZPIGOAXQCGPKMXOURWLDWNZDZSXSIRPPUDVVDDAAIPIULGPKMXOEUSNODSFDEVCIAEQLTHGAEAILDVXLNGPKMXODVURSILIURWLEFHFGPKMXODPAXVXDYAMPMOYPGMIXOXOWGLWXVDPEZFHAPRKURHFFEFHNZFQOFAPQFSFMIOFGPKMXOOFAOVZYEFHNDAZZELSHFABDWAZAPRKURWLNSHFIAIWZLPRPURDUIPDQHPOOBDVCDMGQIXAAMPISXAGQHLDTILDOAPYMIXONUURGHRKHCWZDEYDXVSIEOURWZITBOURPRUTQMEDADEFQHVLODURWLIMLFAZAPRKURDLPRDPQRLDZNQEFHWZYHQHLDGHRKHCFEMIOFDUPRFSBSRTHQGPKMXOOFADLDNSHFSFRTHQNMEQURPRRHONGODCFDUPAVMILDUAIDHYZDUAAPIPLFITUQFHWDATGOZCDZGHRKHCWDRPUAURPRCVUOHQQFOHQILDBYEGTMDZROIMEODAPIURNZFQEFHFAHWDDWOHWMYHQLMIXOANURWDOXWDRDZDODURNHIRPRPYMIXOOFSEAIFEDECDDGUOLDSZAMPIBSTURDZDQDIAVZGDWXYHFDRKURQHPSDAPIURNZFQGPKMXOAPIAURCUIDIYRUGPKMXOEFHFSXSIRPDPEZODIWYVDLFQUVGPKMXONAIUNSANURNZRDSZFDHADAPIUYRKURDETUHCFEMIOFFSDASIKUEDABOBTYIDEZFHAPURFHAXLQFSPYAGFHDZNUURFUGOZCWDGPKMXOLDIRORUFODQFXVVLEUTUQLMIXOOFADLDFSCZDZVXURFHPURNEVLSPIEUFQURWDQDNDDCDZHFEQFDIULDIDYBFELDHFAPIAURWSODPUOFOHONGOURDZAMAIFSLYMIXOURWLSOYBDZOFSERTDSFHDZOXMOCILDBODELFPYMIXOODRNXAVXHOIPGPZNAXIULDHAPIUYRKURDETUHCNDEZNSXOQEDVZQSHKCPAAIPIULGPKMXOXOZDDVSNMSFSEODOHOGPKMXOGOODEFQHGATGWLSIXVFEDEGPZNGPKMXOIMPUOMZYWDAILQHFABPYMIXOIPURDEOFAPQRLDBIQGTZGODAPIEFXVWDMNVXHQWRCHSGSINAIRXFGOCMHGEDPHLDNUQTDZNUCQIDQRLDFDPUGPKMXOOFAEAIDWRKUTONSITANDDCFNHFFNIAKZMOAOLNAPHPAIPIULGHPUFQDZIPURUODSFZQLUETUUEMOZDHAPIEUPRGPHYPHLDGHRKHCFEMIOFSPABOUZYGBFDWMLYDVGHONLDVXDPTVFHWDPYMIXOOFADSVGOYOLDRDPZHGEDPHLDNUQTDZNUCQIDQRLDFDPUAPIAURWSODOFGOOMLQQIGPKMXORDIXEDABDYTUHCNLTIVYMIXOEUDIOAZWFQVPVRITDZUWPVLYGDQFXOWGIGEDAWIAZIMIFDEODUDLOAQFLFTXHGEDAOWGURGONGFOVZELFHGHNF"

#key = [['U','Q','F','B','C'],['O','T','G','V','M'],['Z','Y','W','A','P'],['K','I','N','S','H'],['R','D','X','L','E']]
#key = [['T','G','V','M','O'],['Y','W','A','P','Z'],['I','N','S','H','K'],['D','X','L','E','R'],['Q','F','B','C','U']]
key = [['Y', 'L', 'V', 'G', 'C'], ['W', 'E', 'F', 'N', 'Q'], ['S', 'D', 'A', 'O', 'P'], ['B', 'Z', 'X', 'M', 'K'], ['U', 'H', 'R', 'I', 'T']]


pt = ''.join(q2_helpers.decode(key, ciphertext))

print(pt)
print(q2_helpers.fitness(pt))
max_key = list(key)